language: ruby
rvm:
    - 2.4

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/node_modules

before_install:
    - nvm install 9
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin

before_script: "_ci/setup.sh"
script: "_ci/build.sh"
after_success: "_ci/deploy.sh"

notifications:
    email: false
