

# The Basics
# --------------------
name:                   BigchainDB
description:            'The scalable blockchain database.'
url:                    https://www.bigchaindb.com
ipdb_api_url:           https://test.ipdb.io

email:
    contact:            contact@bigchaindb.com
    contact_cc:         kamal@bigchaindb.com
    cla:                troy@ascribe.io
    cla_cc:             sylvain@bigchaindb.com
    enterprise:         ikytz6br@robot.zapier.com
    enterprise_cc:      kamal@bigchaindb.com

social:
    gitter:
        title:  Gitter
        url:    https://gitter.im/bigchaindb/bigchaindb
    github:
        title:  GitHub
        url:    https://github.com/bigchaindb
        org:    bigchaindb
        repo:   bigchaindb
    twitter:
        title:  Twitter
        handle: bigchaindb
        url:    https://twitter.com/bigchaindb
    facebook:
        title:  Facebook
        handle: bigchaindb
        url:    https://www.facebook.com/BigchainDB/
    medium:
        title:  Blog
        url:    https://blog.bigchaindb.com
    meetup:
        title:  Meetup
        url:    https://www.meetup.com/BigchainDB-IPDB-Meetup
    linkedin:
        title:  LinkedIn
        url:    https://www.linkedin.com/company/bigchaindb
    youtube:
        title:  YouTube
        url:    https://www.youtube.com/bigchaindb

address:
    company:            BigchainDB GmbH
    street:             Wichertstr. 14a
    zip:                10439
    city:               Berlin
    country:            Germany


# Track all the things
# --------------------
analyticsID:            UA-60614729-8
typekitID:              fih1ngo


# Urls
# --------------------
permalink:              /:title/


# Content Parsing
# --------------------
markdown:               redcarpet

redcarpet:
    extensions:         ['no_intra_emphasis', 'autolink', 'tables', 'smart', 'hard_wrap', 'fenced_code_blocks', 'strikethrough', 'highlight', 'quote', 'footnotes', 'with_toc_data', 'space_after_headers', 'superscript', 'lax_spacing']


# Generator
# --------------------
source:                 ./_src
destination:            ./_dist


# Jekyll native collections
# --------------------
collections:
    usecases:
        output: true
        permalink: /:collection/:path/
    partners:
        output: true
        permalink: /:collection/:path/


# Plugins
# --------------------
plugins:
    - jekyll-sitemap
    - jekyll-redirect-from


jekyll_get:
    data: countries
    json: 'https://raw.githubusercontent.com/mledoze/countries/master/dist/countries.json'
