

# The Basics
# --------------------
name:                   BigchainDB
description:            'Coming Soon on February 10'
url:                    https://www.bigchaindb.com

email:
    contact:            contact@bigchaindb.com

twitter:                BigchainDB


# Track all the things
# --------------------
analyticsID:            UA-60614729-8


# Urls
# --------------------
permalink:              /:title/


# Content Parsing
# --------------------
markdown:               redcarpet

redcarpet:
    extensions:         ['autolink', 'smart', 'hard_wrap', 'with_toc_data']


# Generator
# --------------------
source:                 ./_src
destination:            ./_dist


# Plugins
# --------------------
gems:
    - jekyll-sitemap
