

# The Basics
# --------------------
name:                   Bigchain
description:            'The world’s most scalable blockchain.'
url:                    http://www.bigchain.io

email:
    contact:            contact@bigchain.io

twitter:                bigchain
facebook:               bigchain


# Track all the things
# --------------------
analyticsID:            UA-71657563-1


# Urls
# --------------------
permalink:              /:title/


# Content Parsing
# --------------------
markdown:               redcarpet

redcarpet:
    extensions:         ['autolink', 'smart', 'hard_wrap', 'with_toc_data']


# Generator
# --------------------
source:                 ./_src
destination:            ./_dist


# Plugins
# --------------------
gems:
    - jekyll-sitemap
